"""Small ordered schema migrations for SQLite and PostgreSQL."""

from __future__ import annotations

from datetime import UTC, datetime


def apply_migrations(connection, dialect: str) -> None:
    connection.execute("CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL)")
    applied = {row["version"] for row in connection.execute("SELECT version FROM schema_migrations").fetchall()}
    identity = "INTEGER PRIMARY KEY" if dialect == "sqlite" else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    migrations = {1: (
        f"CREATE TABLE IF NOT EXISTS solutions (id {identity}, word TEXT UNIQUE NOT NULL, difficulty TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL)",
        "CREATE TABLE IF NOT EXISTS word_validation_cache (word TEXT PRIMARY KEY, valid INTEGER NOT NULL, definition TEXT, checked_at TEXT NOT NULL)",
    )}
    for version, statements in migrations.items():
        if version not in applied:
            for statement in statements:
                connection.execute(statement)
            connection.execute("INSERT INTO schema_migrations (version, applied_at) VALUES (?, ?)", (version, datetime.now(UTC).isoformat()))
